### ISSUE TITLE
Remove appcompat-v7 from the transitive dependencies list

### ISSUE THREAD

**Issue by SandroMachado** [thiagokimo/Faker#1]
Can you remove the appcompat-v7 from the transitive dependencies list?

**Comment by thiagokimo** [comment]
Hi Sandro! 
I don't think Faker depends on appcompat-v7. Check this out:
https://github.com/thiagokimo/Faker/blob/master/faker-core/build.gradle#L27

I've only used appcompat in the example app. Am I missing something?

**Comment by SandroMachado** [comment]
Hi Thiago,

The Faker depends on RandomColor library that depends on appcompact-v7. I created a PR on the library RandomColor (https://github.com/lzyzsd/AndroidRandomColor/pull/5) to remove this dependency. 
Meanwhile I also created #2 to remove this dependency from this library. 

Removing this unnecessary dependency will reduce the amount of code in the final APK and will not produce compatibility issues if someone needs to use a different version of the app compact library.

**Comment by thiagokimo** [comment]
I totally agree with you :+1: 

I confess that I was a little bit disappointed with myself at the time I've added RandomColor in Faker (I couldn't create good color algorithms like those they use in [here](https://github.com/davidmerfield/randomColor)).

I'll work in those algorithms. Perhaps we could port just them to Faker instead.
