### ISSUE TITLE
Support for Random

### ISSUE THREAD

**Issue by memoeslink** [thiagokimo/Faker#4]
Is there any constructor for Faker that uses a Random? I want to use this library, but it would be nice to have a constructor that passes a Random, so we can set a seed.

**Comment by thiagokimo** [comment]
What do you think about setting a seed through a setter, like in [here](https://github.com/thiagokimo/Faker/commit/0463b4717fd28041bb66537a53ba90790e8175e7)?

**Comment by thiagokimo** [comment]
Fixed with the release 1.4.4
